require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MatchesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Match. As you add validations to Match, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MatchesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all matches as @matches" do
      match = Match.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:matches)).to eq([match])
    end
  end

  describe "GET #show" do
    it "assigns the requested match as @match" do
      match = Match.create! valid_attributes
      get :show, {:id => match.to_param}, valid_session
      expect(assigns(:match)).to eq(match)
    end
  end

  describe "GET #new" do
    it "assigns a new match as @match" do
      get :new, {}, valid_session
      expect(assigns(:match)).to be_a_new(Match)
    end
  end

  describe "GET #edit" do
    it "assigns the requested match as @match" do
      match = Match.create! valid_attributes
      get :edit, {:id => match.to_param}, valid_session
      expect(assigns(:match)).to eq(match)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Match" do
        expect {
          post :create, {:match => valid_attributes}, valid_session
        }.to change(Match, :count).by(1)
      end

      it "assigns a newly created match as @match" do
        post :create, {:match => valid_attributes}, valid_session
        expect(assigns(:match)).to be_a(Match)
        expect(assigns(:match)).to be_persisted
      end

      it "redirects to the created match" do
        post :create, {:match => valid_attributes}, valid_session
        expect(response).to redirect_to(Match.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved match as @match" do
        post :create, {:match => invalid_attributes}, valid_session
        expect(assigns(:match)).to be_a_new(Match)
      end

      it "re-renders the 'new' template" do
        post :create, {:match => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested match" do
        match = Match.create! valid_attributes
        put :update, {:id => match.to_param, :match => new_attributes}, valid_session
        match.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested match as @match" do
        match = Match.create! valid_attributes
        put :update, {:id => match.to_param, :match => valid_attributes}, valid_session
        expect(assigns(:match)).to eq(match)
      end

      it "redirects to the match" do
        match = Match.create! valid_attributes
        put :update, {:id => match.to_param, :match => valid_attributes}, valid_session
        expect(response).to redirect_to(match)
      end
    end

    context "with invalid params" do
      it "assigns the match as @match" do
        match = Match.create! valid_attributes
        put :update, {:id => match.to_param, :match => invalid_attributes}, valid_session
        expect(assigns(:match)).to eq(match)
      end

      it "re-renders the 'edit' template" do
        match = Match.create! valid_attributes
        put :update, {:id => match.to_param, :match => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested match" do
      match = Match.create! valid_attributes
      expect {
        delete :destroy, {:id => match.to_param}, valid_session
      }.to change(Match, :count).by(-1)
    end

    it "redirects to the matches list" do
      match = Match.create! valid_attributes
      delete :destroy, {:id => match.to_param}, valid_session
      expect(response).to redirect_to(matches_url)
    end
  end

end
